<?php

	$common_paths = array(
		"date-format" => "/common/js/date-format.js",
		"sw-overlay" => "/common/js/overlay.js",
		"sw-common" => "/common/js/sw-common.js",
		"sw-input" => "/common/js/sw-input.js",
		"validator" => "/common/js/validator.js",
		"billboard" => "/lib/anim/js/billboard.js",
		"xbutton" => "/lib/button/js/xbutton.js",
		"ed-trans" => "/lib/editor/js/ed-trans.js",
		"ed-util" => "/lib/editor/js/ed-util.js",
		"editor-ext" => "/lib/editor/js/editor-ext.js",
		"editor" => "/lib/editor/js/editor.js",
		"keyboard" => "/lib/editor/js/keyboard.js",
		"ed-kb-html" => "/lib/editor/js/ta/ed-kb-html.js",
		"ed-lang-ta" => "/lib/editor/js/ta/ed-lang-ta.js",
		"translitre" => "/lib/editor/js/translitre.js",
		"ajax" => "/lib/lang/js/ajax.js",
		"dnd" => "/lib/lang/js/dnd.js",
		"dnp" => "/lib/lang/js/dnp.js",
		"lang" => "/lib/lang/js/lang.js",
		"xctxmenu" => "/lib/menu/js/xctxmenu.js",
		"xtree-ctxmenu" => "/lib/tree/js/xtree-ctxmenu.js",
		"xtree" => "/lib/tree/js/xtree.js",
		"base" => "/lib/lang/js/base.js"
	);

	$paths = array(
		"changepwd" => "/account/ui/js/changepwd.js",
		"nu-activation" => "/account/ui/js/nu-activation.js",
		"profile" => "/account/ui/js/profile.js",
		"blog-rpc" => "/blog/ui/js/blog-rpc.js",
		"blog" => "/blog/ui/js/blog.js",
		"cp-config" => "/desk/ui/js/dsk/cp-config.js",
		"desk" => "/desk/ui/js/dsk/desk.js",
		"desktop" => "/desk/ui/js/dsk/desktop.js",
		"explorer" => "/desk/ui/js/dsk/explorer.js",
		"xtaskbar" => "/desk/ui/js/dsk/xtaskbar.js",
		"xwindow" => "/desk/ui/js/dsk/xwindow.js",
		"dsk-rpc" => "/desk/ui/js/dsk-rpc.js",
		"webdesk" => "/desk/ui/js/webdesk.js",
		"xdialog" => "/desk/ui/js/xdiag_wnd.js",
		"news-admin" => "/news/admin/ui/js/admin.js",
		"admin-common" => "/news/admin/ui/js/common.js",
		"admin-search" => "/news/admin/ui/js/search.js",
		"admin-site-grep" => "/news/admin/ui/js/site-greper.js",
		"admin-source" => "/news/admin/ui/js/source.js",
		"admin-url-dd" => "/news/admin/ui/js/url-dd.js",
		"admin-weblinks" => "/news/admin/ui/js/weblinks.js",
		"marquee" => "/news/ui/js/marquee.js",
		"news" => "/news/ui/js/news.js",
		"contact" => "/home/ui/js/contact.js",
		"forgetpwd" => "/home/ui/js/forgetpwd.js",
		"login" => "/home/ui/js/login.js",
		"newuser" => "/home/ui/js/newuser.js",
		"none" => "none"
	);



	$deps = array(
		"cp-config" => array("base","lang"),
		"desktop" => array("cp-config","xctxmenu","dnd","base","xtaskbar","desk","lang"),
		"xdialog" => array("base","xctxmenu","xwindow","xtaskbar","xbutton","lang"),
		"admin-weblinks" => array("sw-overlay","admin-common","sw-common","ajax","date-format","base","admin-site-grep","lang","admin-source"),
		"xtree" => array("base","lang"),
		"explorer" => array("xctxmenu","xwindow","xtaskbar","desk","lang"),
		"changepwd" => array("sw-common","ajax","base","lang","sw-input"),
		"ajax" => array("base"),
		"ed-util" => array("base","lang"),
		"login" => array("base"),
		"dsk-rpc" => array("ajax","base"),
		"ed-kb-html" => array("base"),
		"marquee" => array("base","lang"),
		"xctxmenu" => array("lang"),
		"ed-lang-ta" => array("ed-trans","ed-kb-html","keyboard","translitre","xctxmenu","base","xwindow","xtaskbar","lang"),
		"ed-trans" => array("keyboard","translitre","base","xctxmenu","xwindow","xtaskbar","lang"),
		"editor" => array("ed-trans","ed-kb-html","keyboard","translitre","ed-util","base","xctxmenu","xwindow","xtaskbar","lang","ed-lang-ta","editor-ext"),
		"admin-url-dd" => array("sw-common","admin-common","ajax","base","date-format","lang"),
		"sw-overlay" => array("sw-common","base","lang"),
		"admin-search" => array("admin-url-dd","sw-overlay","admin-common","sw-common","validator","ajax","date-format","base","admin-site-grep","lang","admin-source"),
		"date-format" => array("lang"),
		"billboard" => array("base","lang"),
		"admin-site-grep" => array("sw-overlay","admin-common","sw-common","ajax","date-format","base","lang"),
		"validator" => array("base","date-format","lang"),
		"desk" => array("lang"),
		"blog" => array("xtree","sw-common","ajax","base","blog-rpc","lang"),
		"lang" => array("base"),
		"editor-ext" => array("ed-trans","keyboard","ed-kb-html","translitre","ed-util","xctxmenu","base","xwindow","xtaskbar","ed-lang-ta","lang"),
		"contact" => array("ajax","base","lang","sw-input", "sw-common"),
		"admin-source" => array("sw-overlay","sw-common","admin-common","ajax","base","date-format","admin-site-grep","lang"),
		"xtree-ctxmenu" => array("xtree","xctxmenu","base","lang"),
		"newuser" => array("ajax","base","lang","sw-input", "sw-common"),
		"translitre" => array("base"),
		"admin-common" => array("sw-common","ajax","date-format","base","lang"),
		"dnd" => array("base","lang"),
		"xwindow" => array("xctxmenu","xtaskbar","lang"),
		"blog-rpc" => array("ajax","base"),
		"profile" => array("sw-common","ajax","base","lang","sw-input"),
		"webdesk" => array("dsk-rpc","ed-kb-html","keyboard","cp-config","xctxmenu","desktop","xtaskbar","xbutton","desk","editor-ext","ed-lang-ta","lang","ed-trans","explorer","editor","translitre","ajax","ed-util","dnd","base","xwindow"),
		"keyboard" => array("xctxmenu","xwindow","xtaskbar","lang"),
		"news" => array("marquee","sw-common","ajax","base","lang"),
		"dnp" => array("base"),
		"forgetpwd" => array("ajax","base","lang","sw-input","sw-common"),
		"xtaskbar" => array("xctxmenu","lang"),
		"xbutton" => array("base","lang"),
		"news-admin" => array("admin-url-dd","sw-overlay","sw-common","admin-common","admin-search","ajax","validator","base","date-format","admin-site-grep","admin-weblinks","lang","admin-source"),
		"sw-common" => array("base","lang"),
		"nu-activation" => array("sw-common","ajax","base","lang","sw-input"),
		"sw-input" => array("base","lang","sw-common"),
		""
	);

?>
